name:                pandoc-github
version:             0.1.0.0
github:              "eamsden/pandoc-github"
license:             BSD3
author:              "Edward Amsden"
maintainer:          "edwardamsden@gmail.com"
copyright:           "2018 Edward Amsden"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/eamsden/pandoc-github#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc
- github
- bytestring
- text
- optparse-applicative

library:
  source-dirs: src

executables:
  pandoc-github:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-github

tests:
  pandoc-github-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-github
